### ISSUE TITLE
what is the use of cookie.txt ?

### ISSUE THREAD

**Issue by AntroFyo** [dlrudco/Fast-Audioset-Download#1]

**Comment by dlrudco** [comment]
The cookie.txt is for the authentication(sort of). Without this, youtube-dl might fail to fetch some of the videos.  I used this mozilla firefox extension(https://addons.mozilla.org/ko/firefox/addon/cookies-txt/) to create the cookies.txt file. I found that you should not be logged into your own youtube-account when you create a cookie file since it will make your youtube streaming very unstable elsewhere. Thus, create the cookie file while being logged out. 


** I have finished downloading all of the dataset using this code. However, this repo is still very buggy so i will update to a more stable version soon.

**Comment by AntroFyo** [comment]
Yep and thanks!  i have tried many github projects to download audioset. However, due to the internet i could not use you-get and other tools. That makes me upset....

**Comment by dlrudco** [comment]
Just uploaded a modified version of the downloading script. I removed the parmap dependency and switched to multiprocessing.Pool which seems to be more stable. make sure you have also installed ffmpeg in your machine or conda environment when using. I have updated README.md too. 

I will now close this issue, but if there's any other questions please let me know :)
