### ISSUE TITLE
final stats for data that can be downloaded

### ISSUE THREAD

**Issue by sukun1045** [dlrudco/Fast-Audioset-Download#4]
Hi, thanks for this useful script. Could you share the number of videos that could download for eval/balanced_train/unbalanced_train since I realize some videos are no longer available? I just want to make sure I download them correctly. thank you.

**Comment by dlrudco** [comment]
Sorry for the late reply... This was also a serious issue for me. However, I could not solve it myself. Only remedy I could do was to try multiple times for the failure cases. 

So I am sorry to inform you that right now I am also not entirely sure for the final statistics, since while I was trying it kept changing due to various issues. I only confirmed that this repo could harvest fair amount of data, which was sufficient for me.
