### ISSUE TITLE
json file vanished

### ISSUE THREAD

**Issue by fundwotsai2001** [dlrudco/Fast-Audioset-Download#6]
Hello, thanks for your impressive work! After I download the eval and balance train folder, the json files are gone, and i could not access the labels. Did you intentionally do this, or this is a bug. Thanks~

**Comment by dlrudco** [comment]
I am afraid I cannot understand your question. Maybe you are mentioning about clearing the intermediate json files? If the "audioset_metadata.json" file is present on the main folder, the process is done. This is because I intentionally made my code to clear all the temporary json labels for each files and save one big label json file merging all. 

If this is not what you intended to ask me, can you please elaborate on your issue so I can look into it? :)

**Comment by fundwotsai2001** [comment]
Oh~ I understand how it works now, I didn't realize that the json files that have the same file names with the audio are temporary, now i see the merged json files. Thanks for your quick reply~

**Comment by dlrudco** [comment]
:thumbsup:
